# Generated by Django 3.1.4 on 2021-11-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogpost',
            new_name='Blog',
        ),
    ]
